########################################################################
# Copyright (c) 1988-2018 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 10/18/2018
#
# generic Gcc Makefile for nadir Executable xoshello
########################################################################


#
# target
#
xoshello_EXETARGET = xoshello

########################################################################

#
# user c++ flags
#
xoshello_USRCXXFLAGS += \
${xosnadir_USRCXXFLAGS} \

#
# user defines
#
xoshello_USRDEFINES += \
${xosnadir_USRDEFINES} \

#
# user includes
#
xoshello_USRINCLUDES += \
${xosnadir_USRINCLUDES} \

#
# user libdirs
#
xoshello_USRLIBDIRS += \
${xosnadir_USRLIBDIRS} \

########################################################################

#
# Executable .c sources
#
#xoshello_EXE_C_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.c \

#
# Executable .cc sources
#
#xoshello_EXE_CC_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.cc \

#
# Executable .cxx sources
#
#xoshello_EXE_CXX_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.cxx \

#
# Executable .cpp sources
#
xoshello_EXE_CPP_SOURCES += \
${NADIR_SRC}/xos/app/console/hello/main.cpp \

#
# Executable .m sources
#
#xoshello_EXE_M_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.m \

#
# Executable .mm sources
#
#xoshello_EXE_MM_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.mm \


########################################################################

#
# Executable libraries
#
xoshello_LIBS += \
${xosnadir_LIBS}



