########################################################################
# Copyright (c) 1988-2018 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 3/22/2018
#
# generic Gcc Makefile for nadir Library libxosnadir
########################################################################


#
# target
#
libxosnadir_LIBTARGET = libxosnadir.${LIBEXT}

########################################################################

#
# user c++ flags
#
libxosnadir_USRCXXFLAGS += \
${xosnadir_USRCXXFLAGS} \

#
# user defines
#
libxosnadir_USRDEFINES += \
${xosnadir_USRDEFINES} \

#
# user includes
#
libxosnadir_USRINCLUDES += \
${xosnadir_USRINCLUDES} \

#
# user libdirs
#
libxosnadir_USRLIBDIRS += \
${xosnadir_USRLIBDIRS} \

########################################################################

#
# Library .c sources
#
#libxosnadir_LIB_C_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.c \

#
# Library .cc sources
#
#libxosnadir_LIB_CC_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.cc \

#
# Library .cxx sources
#
#libxosnadir_LIB_CXX_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.cxx \

#
# Library .cpp sources
#
libxosnadir_LIB_CPP_SOURCES += \
${NADIR_SRC}/xos/base/getopt/main_opt.cpp \
${NADIR_SRC}/xos/base/getopt/main.cpp \
${NADIR_SRC}/xos/base/string.cpp \
${NADIR_SRC}/xos/base/created.cpp \
${NADIR_SRC}/xos/base/creator.cpp \
${NADIR_SRC}/xos/base/create.cpp \
${NADIR_SRC}/xos/base/opened.cpp \
${NADIR_SRC}/xos/base/opener.cpp \
${NADIR_SRC}/xos/base/open.cpp \
${NADIR_SRC}/xos/base/attacher.cpp \
${NADIR_SRC}/xos/base/attach.cpp \
${NADIR_SRC}/xos/base/array.cpp \
${NADIR_SRC}/xos/base/base.cpp \
\
${NADIR_SRC}/xos/io/file/reader.cpp \
${NADIR_SRC}/xos/io/file/writer.cpp \
${NADIR_SRC}/xos/io/main/logger.cpp \
\
${NADIR_SRC}/xos/mt/acquire.cpp \
${NADIR_SRC}/xos/mt/acquirer.cpp \
${NADIR_SRC}/xos/mt/releaser.cpp \
${NADIR_SRC}/xos/mt/lock.cpp \
${NADIR_SRC}/xos/mt/locker.cpp \
${NADIR_SRC}/xos/mt/wait.cpp \
${NADIR_SRC}/xos/mt/waiter.cpp \
\
${NADIR_SRC}/xos/mt/os/semaphore.cpp \
${NADIR_SRC}/xos/mt/os/mutex.cpp \

#
# Library .m sources
#
#libxosnadir_LIB_M_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.m \

#
# Library .mm sources
#
#libxosnadir_LIB_MM_SOURCES += \
#${NADIR_SRC}/nadir/base/Base.mm \


########################################################################




