########################################################################
# Copyright (c) 1988-2017 $organization$
#
# This software is provided by the author and contributors ``as is''
# and any express or implied warranties, including, but not limited to,
# the implied warranties of merchantability and fitness for a particular
# purpose are disclaimed. In no event shall the author or contributors
# be liable for any direct, indirect, incidental, special, exemplary,
# or consequential damages (including, but not limited to, procurement
# of substitute goods or services; loss of use, data, or profits; or
# business interruption) however caused and on any theory of liability,
# whether in contract, strict liability, or tort (including negligence
# or otherwise) arising in any way out of the use of this software,
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 8/30/2017
#
# generic Gcc Makefile for nadir Shared Library libnadir
########################################################################

#
# target
#
libnadir_LIBTARGET = libnadir.$(LIBEXT)

#
# user c++ flags
#
libnadir_USRCXXFLAGS += \
${nadir_USRCXXFLAGS} \

#
# user defines
#
libnadir_USRDEFINES = \
${nadir_USRDEFINES} \

#
# user includes
#
libnadir_USRINCLUDES = \
${nadir_USRINCLUDES} \

#
# user libdirs
#
libnadir_USRLIBDIRS = \
${nadir_USRLIBDIRS} \

#
# C++ .cpp sources
#
libnadir_LIB_CPP_SOURCES += \
${NADIR_SRC}/xos/base/Base.cpp \
${ROSTRA_SRC}/xos/platform/platform.cpp \

