########################################################################
# Copyright (c) 1988-2014 $organization$
#
# This software is provided by the author and contributors ``as is'' 
# and any express or implied warranties, including, but not limited to, 
# the implied warranties of merchantability and fitness for a particular 
# purpose are disclaimed. In no event shall the author or contributors 
# be liable for any direct, indirect, incidental, special, exemplary, 
# or consequential damages (including, but not limited to, procurement 
# of substitute goods or services; loss of use, data, or profits; or 
# business interruption) however caused and on any theory of liability, 
# whether in contract, strict liability, or tort (including negligence 
# or otherwise) arising in any way out of the use of this software, 
# even if advised of the possibility of such damage.
#
#   File: Makefile
#
# Author: $author$
#   Date: 11/17/2014
#
# Gcc Makefile for nadir
########################################################################
#
# XOS defines
#
XOS_SRC = $(PKG)/$(SRC)

#
# user includes
#
xos_USRINCLUDES += \
-I${XOS_SRC} \

#
# user defines
#
xos_USRDEFINES += \

#
# user c++ flags
#
xos_USRCXXFLAGS += \

#
# user c flags
#
xos_USRCFLAGS += \

#
# user ld flags
#
xos_USRLDFLAGS += \

#
# user libdirs
#
xos_USRLIBDIRS += \

#
# libs
#
#LIBS = \
#-lsomelib
#
xos_LIBS += \
-lxosnadir \

#
# depend
#
#DEP = \
#$(PKG)/$(BLD)/libsomelib \
#
xos_DEP += \

#
# depend dirs
#
#DEP_DIRS = \
#../libsomelib
#
xos_DEP_DIRS += \


